name: firebase_auth_riverpod
description: "A Guide for implementing Firebase Authentication with Flutter Riverpod and Go Router"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.2.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  build_runner: ^2.4.12


flutter:
  uses-material-design: true